/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultisigContractAbi } from "./MultisigContractAbi";

export { MultisigContractAbi__factory } from "./factories/MultisigContractAbi__factory";
